import { randomUUID } from 'node:crypto';
import { eq } from 'drizzle-orm';
import type { DbTx } from '../db/with-actor';
import { outbox } from '../db/schema';

export interface ThreadingHeaders {
  inReplyTo?: string | null;
  references?: string | null;
  /** Auto-ack sets this so external auto-responders don't ping-pong (NFR11 layer 3). */
  autoSubmitted?: boolean;
}

export interface EnqueueInput {
  projectId: number;
  to: string[];
  cc?: string[];
  bcc?: string[];
  subject: string;
  bodyHtml?: string | null;
  bodyText?: string | null;
  /** Threading headers, stored as JSON and applied by the sender (FR7). */
  headers?: ThreadingHeaders;
  ticketId?: string;
  /** RFC Message-ID of the outbound mail — SAME value stored on ticket_messages so
   *  a later inbound reply threads back (FR7). Generated by the caller. */
  messageId: string;
  /** Dedup guard: two enqueues with the same key collapse to one row (AC4). */
  idempotencyKey?: string;
}

export interface EnqueueResult {
  outboxId: string;
  /** True when an existing row with the same idempotency_key was reused. */
  deduped: boolean;
}

/** Stable Message-ID for an outbound mail, scoped to the project mailbox domain. */
export function generateMessageId(fromAddress: string): string {
  const domain = fromAddress.includes('@') ? fromAddress.split('@')[1] : 'pmh.com.vn';
  return `<${randomUUID()}@${domain}>`;
}

/**
 * The ONE way business email leaves the system (CLAUDE.md invariant #4): callers
 * enqueue IN THEIR OWN transaction (atomic with the business change), the worker's
 * outbox loop sends at-least-once. Lives in infra/queue (not email-engine) because
 * tickets/intake/notifications all call it — putting it in a leaf module would make
 * leaf-import-leaf (party-mode W6). OTP/reset stay on the direct Mailer.
 */
export async function enqueue(tx: DbTx, input: EnqueueInput): Promise<EnqueueResult> {
  const idempotencyKey = input.idempotencyKey ?? randomUUID();

  const rows = await tx
    .insert(outbox)
    .values({
      projectId: input.projectId,
      toAddrs: input.to,
      ccAddrs: input.cc ?? null,
      bccAddrs: input.bcc ?? null,
      subject: input.subject,
      bodyHtml: input.bodyHtml ?? null,
      bodyText: input.bodyText ?? null,
      headers: input.headers ? JSON.stringify(input.headers) : null,
      ticketId: input.ticketId ?? null,
      messageId: input.messageId,
      idempotencyKey,
    })
    .onConflictDoNothing({ target: outbox.idempotencyKey })
    .returning({ id: outbox.id });

  if (rows.length > 0) return { outboxId: rows[0]!.id, deduped: false };

  // Conflict on idempotency_key → reuse the existing row (at-least-once, exactly-enqueued).
  const [existing] = await tx
    .select({ id: outbox.id })
    .from(outbox)
    .where(eq(outbox.idempotencyKey, idempotencyKey));
  // Under READ COMMITTED a concurrent enqueue of the SAME deterministic key can leave
  // the conflicting (still-uncommitted) row invisible to this SELECT. Throw a clear
  // error instead of dereferencing undefined (only deterministic-key callers, e.g.
  // auto-ack in the serialized intake pipeline, can ever reach this branch).
  if (!existing) throw new Error('outbox enqueue race: conflicting row not yet visible');
  return { outboxId: existing.id, deduped: true };
}
